global:
  extra_config: /app/extra-config.json
  variables:
    KEYCLOAK_URL: http://keycloak:8080/keycloak
    REALM_NAME: optimce-realm
    ISSUER: http://localhost:8087/keycloak/realms/optimce-realm

services:
  root:
    swagger: /config/root.yaml
    host: crm-backend:80
  generation:
    swagger: /config/generation.json
    host: allocation-key-generation:8000
  simulation:
    swagger: /config/simulation.json
    host: simulation-key:8000
  news:
    swagger: /config/news.json
    host: optimce-news-board:8000
  billing:
    swagger: /config/billing.json
    host: billing:8000
