#!/usr/bin/env python3
"""Exactly ONE endpoint in the generated gateway config may be unauthenticated.

================================================================================
WHY THIS SCRIPT EXISTS SEPARATELY FROM THE TWO GATES INSIDE live-data.

`live-data` guards its public surface twice already:

  1. `scripts/export_openapi.py` asserts the public OPERATION SET *equals* a
     hard-coded literal, and refuses to write either spec otherwise.
  2. `tests/test_public_surface.py` asserts the public routes' DEPENDENCY TREES
     are clean and - inversely - that nothing else is dependency-free.

Both of those reason about the SERVICE. Neither can see what the GATEWAY
publishes, and that is where a route actually becomes reachable without a token.
`krakend.json` is generated by the builder from per-service JSON, and KrakenD's
JWT validator is configured **per service entry, never per endpoint** - which is
why live-data needs two entries in the first place. A mistake in the builder, in
`krakend-builder.yaml`, or in a hand-edit of a generated file publishes an
authenticated route without its validator, and nothing in this repository fails:
KrakenD boots, the route answers, and the only symptom is that it answers
everybody.

Both files above have cited this script as "gate 3" since build step 4. It did
not exist. That is the failure this file closes, and it is the one worth naming:
a guard that is DOCUMENTED and absent is more dangerous than one that was never
claimed, because every reader downstream stops looking.
================================================================================

Run it after regenerating the gateway config:

    python scripts/verify-krakend-public-surface.py

Exit 0 = the surface is what it should be. Exit 1 = read the message; it names
every offending endpoint. Exit 2 = the config is missing, which is not a pass.
"""

from __future__ import annotations

import json
import pathlib
import sys

_ROOT = pathlib.Path(__file__).resolve().parents[1]
_CONFIG = _ROOT / "krakend" / "config" / "krakend.json"

# The one endpoint the platform intends to publish without a token, and the only
# unauthenticated entry point in the whole gateway. A device holds an enrolment
# code, never a session; `nginx` blanks the five `x-user-*` trust headers for
# this exact path because KrakenD's `input_headers` is global and cannot.
#
# ADDING TO THIS SET IS A SECURITY DECISION, NOT A BUILD FIX. It mirrors
# `PUBLIC_OPERATIONS` in live-data/api/live_public/routes.py, and the two must be
# changed together and reviewed together.
PUBLIC_ENDPOINTS: frozenset[tuple[str, str]] = frozenset(
    {
        ("/live-public/enroll", "POST"),
    }
)

# What KrakenD's `extra_config` key for JWT validation is called. An endpoint
# carrying any OTHER extra_config - a rate limiter, a circuit breaker - is still
# unauthenticated, so presence of `extra_config` is NOT the test.
_VALIDATOR = "auth/validator"


def main() -> int:
    if not _CONFIG.exists():
        print(f"FAIL  {_CONFIG} does not exist.", file=sys.stderr)
        print(
            "      It is generated - run the krakend-config one-shot first.\n"
            "      A missing config is not a passing check.",
            file=sys.stderr,
        )
        return 2

    config = json.loads(_CONFIG.read_text(encoding="utf-8"))
    endpoints = config.get("endpoints", [])
    if not endpoints:
        print("FAIL  the generated config declares no endpoints at all.", file=sys.stderr)
        return 2

    unauthenticated = {
        (endpoint.get("endpoint", "?"), endpoint.get("method", "GET"))
        for endpoint in endpoints
        if _VALIDATOR not in endpoint.get("extra_config", {})
    }

    unexpected = sorted(unauthenticated - PUBLIC_ENDPOINTS)
    missing = sorted(PUBLIC_ENDPOINTS - unauthenticated)

    for path, method in unexpected:
        print(
            f"FAIL  {method} {path} is published WITHOUT `{_VALIDATOR}`.\n"
            f"      Anyone on the internet can call it. If that is intended, add it to\n"
            f"      PUBLIC_ENDPOINTS here AND to PUBLIC_OPERATIONS in\n"
            f"      live-data/api/live_public/routes.py - both, deliberately.",
            file=sys.stderr,
        )

    # The inverse, and the one a "no unexpected public routes" check would miss:
    # the enrolment leg silently acquiring a validator means every device fails to
    # enrol, with a 401 that looks like a credential problem on the device.
    for path, method in missing:
        print(
            f"FAIL  {method} {path} is meant to be public and now carries "
            f"`{_VALIDATOR}`.\n"
            f"      No device can enrol: the gateway rejects the call before the\n"
            f"      service sees it, and the failure looks like a bad token on the\n"
            f"      device rather than a gateway change.",
            file=sys.stderr,
        )

    if unexpected or missing:
        return 1

    print(
        f"ok  {len(endpoints)} endpoint(s); exactly {len(PUBLIC_ENDPOINTS)} unauthenticated, "
        f"and it is the one it should be."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
